version: '2'
services:
  iot_button:
    build: ./
    network_mode: "host"
    volumes:
      - ./logs:/home/iot/logs
      - ./config:/home/iot/config
      - /etc/localtime:/etc/localtime:ro
    restart: always